### ISSUE TITLE
Not getting any outputs. Does it still work?

### ISSUE THREAD

**Issue by undefinedCody** [qg5/telegram-username-sniper#1]
Hi, I just installed go1.23rc2.linux-amd64.tar.gz on my linux, filled the necessary information on config.json and ran your script. At first I got bunch of these errors upon running `go run main.go`:

```
../../telegram/client.go:7:2: missing go.sum entry for module providing package github.com/gotd/td/session (imported by app/telegram); to add:                          
        go get app/telegram                                                  
../../telegram/client.go:8:2: missing go.sum entry for module providing package github.com/gotd/td/telegram (imported by app/telegram); to add:                         
        go get app/telegram                                                  
../../telegram/auth_flow.go:9:2: missing go.sum entry for module providing package github.com/gotd/td/telegram/auth (imported by app/telegram); to add:                 
        go get app/telegram                                                  
../../telegram/auth_flow.go:10:2: missing go.sum entry for module providing package github.com/gotd/td/tg (imported by app/telegram); to add:                           
        go get app/telegram                                                         
../../telegram/client.go:11:2: missing go.sum entry for module providing package github.com/gotd/td/tgerr (imported by app/telegram); to add:                           
        go get app/telegram                                                                                                                                             
../../telegram/auth_flow.go:11:2: missing go.sum entry for module providing package golang.org/x/term (imported by app/telegram); to add:                                                
        go get app/telegram
```

But it was solved quickly using `go get app/telegram`. Now when I run `go run main.go`, I do not see any outputs in my terminal and I even tested it using a dummy username and it didn't claim the username.
The instruction was pretty clear so I don't think I'm doing anything wrong.

Does your script still work? If so, could you please tell me if there are any solutions?

--
Downgraded to Go 1.22.2 and it made no difference.

**Comment by qg5** [comment]
Hello, sorry just saw this issue.

Have you tried `go mod tidy`?

edit: ensure the credentials in the `config.json` are correct as well as the format for the phone number being in international format (ie: +11074062284)

**Comment by qg5** [comment]
and regarding your main question, the script does work in my case and i have the same code in this repo, if you wish to contact me in telegram to have the issue sorted out faster, feel welcome to :)

tg: waquan

**Comment by undefinedCody** [comment]
Oh hi, thanks for getting back to me.
That night I was in such a hurry that I spent a couple of hours and wrote my own script in Python.

But thank you for your great project, it was a huge inspiration.

Cheers

**Comment by qg5** [comment]
glad to hear that! hope you get some snipes, best of luck :)

pd; sorry for replying 4 days after
