### ISSUE TITLE
Sending single request

### ISSUE THREAD

**Issue by ghost** [qg5/telegram-username-sniper#2]
When a specified user is taken it only sends out one request in attempt to claim it, not sure if im doing anything wrong if so plz lmk.

**Comment by qg5** [comment]
nothing is wrong, once an attempt to claim is done, it removes the username from the list, if you think this behavior is wrong, feel free to recommend a feature :)

perhaps we can have a max of 5 claim attempts for each username before removing it from the list?

**Comment by ghost** [comment]
I see, what doesn't make sense to me is if you were to attempt to claim/snipe a username that is inactive by having the program running this wouldn't be possible because it only sends out one request in attempt to claim it. The only way you would be able to claim an inactive username using this is if you were to know when it gets deleted and open the program then. Which still would be pointless bc ur better off just hand claiming it if you can. It would be more efficient and have higher success chances in claming / sniping the username if it has a customizable rps / attempts to claim thing that is optional idk. Its kinda hard to explain hopefully you understand, this obviously wont be easy to add but would make things alot smoother for claiming/sniping the username and would give the people who use this program a variety of options to choose from rather then using this as a username swapper. Note: i saw that proxies isn't checked, maybe this is a feature that will be implemented soon?

**Comment by qg5** [comment]
there isn't really a certain way to know when a username will get deleted other than if the status for that username is "Last seen a long time ago" which would indicate that they've been offline for more than a month, the default setting for telegram accounts is that their account will be deleted after 6 months of inactivity

I will look into implementing that feature and implementing proxies if possible for sure, thank you so much for mentioning it :)

Eta for the update: **2 days** and I will have it pushed as well as a new release uploaded so you can set it up quicker, if you want me to update you through telegram, drop your handle here and I will personally shoot you a dm as soon as it's pushed

**Comment by qg5** [comment]
forgot to clarify about this part:

> I see, what doesn't make sense to me is if you were to attempt to claim/snipe a username that is inactive by having the program running this wouldn't be possible because it only sends out one request in attempt to claim it

so, the program sends 1 request only after the username becomes available, it doesn't constantly send requests to claim it, first it checks if it's available for claiming and THEN it claims it, hope that makes it clear, i'm not the best at explaining either
